export const skillsData = [
    {
        label:"Front End",
        data:[
            {
                skillName:"HTML",
                percentage:"90",
            },
            {
                skillName:"CSS",
                percentage:"90",
            },
            {
                skillName:"JAVASCRIPT",
                percentage:"80",
            },
            {
                skillName:"REACT",
                percentage:"80",
            },
            {
                skillName:"TAILWINDCSS",
                percentage:"50",
            },
        ]
    },
    {
        label:"BACKEND",
        data:[
            {
              skillName:"NODE JS",
              percentage:"50"
            },
            {
              skillName:"EXPRESS JS",
              percentage:"50"
            },
            {
              skillName:"JAVA",
              percentage:"80"
            },
        ]
    },
    {
        label:"DATABASES",
        data:[
            {
              skillName:"MONGODB",
              percentage:"80"
            },
        ]
    }
]